# Generated by Django 4.2.5 on 2023-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='img',
            field=models.ImageField(blank=True, upload_to='element'),
        ),
    ]
