# Generated by Django 4.2.5 on 2023-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
