# Generated by Django 4.2.5 on 2023-11-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_element_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='img',
            new_name='image',
        ),
    ]
